package service

// Behavioral tests for ReissueBotToken — the authz rejection matrix
// and the revoke-then-issue effect. These pin the load-bearing security
// properties: a regression that weakens the ownership check or leaves
// old tokens authenticating after rotation would pass every other test
// but fail here.

import (
	"errors"
	"testing"

	"github.com/enju-ai/enju/internal/coordinator/store"
)

// newReissueStore opens an in-memory store wired with an event store.
// Mirrors the setup in store/sqlite_test.go:newTestStore.
func newReissueStore(t *testing.T) *store.Store {
	t.Helper()
	s, err := store.New(":memory:")
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	dir := t.TempDir()
	es, err := store.NewSQLiteEventStore(dir+"/events.db", nil)
	if err != nil {
		t.Fatalf("attach event store: %v", err)
	}
	s.AttachEventStore(es)
	t.Cleanup(func() {
		s.Close()
		es.Close()
	})
	return s
}

// makeHuman creates a human citizen and returns its record.
func makeHuman(t *testing.T, s *store.Store, username, token string) *store.CitizenRecord {
	t.Helper()
	_, err := s.ApplyPlan(store.Plan{
		Version: store.TestEngineVersion,
		Mutations: []store.Mutation{
			store.CreateCitizen{
				Citizen: store.CitizenRecord{
					Username: username,
					Name:     username,
					Email:    username + "@test.local",
					Kind:     store.CitizenKindHuman,
				},
				Token: token,
			},
		},
	})
	if err != nil {
		t.Fatalf("create human %s: %v", username, err)
	}
	c, err := s.GetCitizenByUsername(username)
	if err != nil || c == nil {
		t.Fatalf("get human %s: %v / %v", username, err, c)
	}
	return c
}

// makeAgent creates a bot citizen parented by owner and returns its record.
// The initial token is generated by RegisterBot; callers that need it can
// read it from the returned RegisterBotResponse before this helper discards it.
func makeAgent(t *testing.T, s *store.Store, owner *store.CitizenRecord, agentName string) *store.CitizenRecord {
	t.Helper()
	resp, err := RegisterBot(s, owner, RegisterBotParams{
		Name:     agentName,
		Username: agentName,
	})
	if err != nil {
		t.Fatalf("register agent %s: %v", agentName, err)
	}
	c, err := s.GetCitizenByUsername(resp.Username)
	if err != nil || c == nil {
		t.Fatalf("get agent %s: %v / %v", agentName, err, c)
	}
	return c
}

// makeAgentWithToken is like makeAgent but also returns the initial token.
func makeAgentWithToken(t *testing.T, s *store.Store, owner *store.CitizenRecord, agentName string) (*store.CitizenRecord, string) {
	t.Helper()
	resp, err := RegisterBot(s, owner, RegisterBotParams{
		Name:     agentName,
		Username: agentName,
	})
	if err != nil {
		t.Fatalf("register agent %s: %v", agentName, err)
	}
	c, err := s.GetCitizenByUsername(resp.Username)
	if err != nil || c == nil {
		t.Fatalf("get agent %s: %v / %v", agentName, err, c)
	}
	return c, resp.Token
}

// TestReissueBotToken_OwnerCanRotate is the happy path: the owner
// calls ReissueBotToken, gets a fresh token, and it authenticates.
func TestReissueBotToken_OwnerCanRotate(t *testing.T) {
	s := newReissueStore(t)
	owner := makeHuman(t, s, "alice", "alice-tok")
	_, oldToken := makeAgentWithToken(t, s, owner, "dev-bot")

	resp, err := ReissueBotToken(s, owner, "dev-bot", "")
	if err != nil {
		t.Fatalf("ReissueBotToken: %v", err)
	}
	if resp.Token == "" {
		t.Fatal("got empty token")
	}
	if resp.Token == oldToken {
		t.Fatal("token was not rotated — same value returned")
	}
	c, err := s.GetCitizenByToken(resp.Token)
	if err != nil || c == nil {
		t.Fatalf("new token does not authenticate: %v / %v", err, c)
	}
	if c.Username != "dev-bot" {
		t.Errorf("new token authenticated as %q, want dev-bot", c.Username)
	}
}

// TestReissueBotToken_OldTokenRevoked ensures the old token stops
// authenticating after rotation — the core "leaked token cannot
// outlive rotation" guarantee.
func TestReissueBotToken_OldTokenRevoked(t *testing.T) {
	s := newReissueStore(t)
	owner := makeHuman(t, s, "alice", "alice-tok")
	_, oldToken := makeAgentWithToken(t, s, owner, "dev-bot")

	if _, err := ReissueBotToken(s, owner, "dev-bot", ""); err != nil {
		t.Fatalf("ReissueBotToken: %v", err)
	}

	c, err := s.GetCitizenByToken(oldToken)
	if err != nil {
		t.Fatalf("lookup old token: %v", err)
	}
	if c != nil {
		t.Errorf("old token still authenticates after rotation — auth bypass")
	}
}

// TestReissueBotToken_NotOwner_Forbidden: a different human who does
// not parent the agent must get ErrForbidden.
func TestReissueBotToken_NotOwner_Forbidden(t *testing.T) {
	s := newReissueStore(t)
	owner := makeHuman(t, s, "alice", "alice-tok")
	other := makeHuman(t, s, "bob", "bob-tok")
	makeAgent(t, s, owner, "dev-bot")

	_, err := ReissueBotToken(s, other, "dev-bot", "")
	if err == nil {
		t.Fatal("expected ErrForbidden, got nil")
	}
	if !errors.Is(err, ErrForbidden) {
		t.Errorf("expected ErrForbidden, got %v", err)
	}
}

// TestReissueBotToken_TargetIsHuman_Forbidden: a human citizen
// (kind != agent) must be rejected — callers cannot rotate a human's
// token via this path.
func TestReissueBotToken_TargetIsHuman_Forbidden(t *testing.T) {
	s := newReissueStore(t)
	caller := makeHuman(t, s, "alice", "alice-tok")
	makeHuman(t, s, "bob", "bob-tok")

	_, err := ReissueBotToken(s, caller, "bob", "")
	if err == nil {
		t.Fatal("expected ErrForbidden, got nil")
	}
	if !errors.Is(err, ErrForbidden) {
		t.Errorf("expected ErrForbidden, got %v", err)
	}
}

// TestReissueBotToken_NotFound: a username that doesn't exist must
// return ErrNotFound, not a nil-pointer panic.
func TestReissueBotToken_NotFound(t *testing.T) {
	s := newReissueStore(t)
	caller := makeHuman(t, s, "alice", "alice-tok")

	_, err := ReissueBotToken(s, caller, "ghost-bot", "")
	if err == nil {
		t.Fatal("expected ErrNotFound, got nil")
	}
	if !errors.Is(err, ErrNotFound) {
		t.Errorf("expected ErrNotFound, got %v", err)
	}
}

// TestReissueBotToken_AgentOwnerlessRejected: an agent whose ParentID
// is nil (edge case — not producible via RegisterBot, but defensible)
// must be rejected.
func TestReissueBotToken_AgentOwnerlessRejected(t *testing.T) {
	s := newReissueStore(t)
	caller := makeHuman(t, s, "alice", "alice-tok")
	// Create a parentless agent directly via plan mutation.
	_, err := s.ApplyPlan(store.Plan{
		Version: store.TestEngineVersion,
		Mutations: []store.Mutation{
			store.CreateCitizen{
				Citizen: store.CitizenRecord{
					Username: "orphan-bot",
					Name:     "orphan-bot",
					Email:    "orphan-bot@test.local",
					Kind:     store.CitizenKindAgent,
					// ParentID intentionally nil
				},
				Token: "orphan-tok",
			},
		},
	})
	if err != nil {
		t.Fatalf("create orphan agent: %v", err)
	}

	_, err = ReissueBotToken(s, caller, "orphan-bot", "")
	if err == nil {
		t.Fatal("expected ErrForbidden, got nil")
	}
	if !errors.Is(err, ErrForbidden) {
		t.Errorf("expected ErrForbidden, got %v", err)
	}
}

// TestReissueBotToken_LabelPreserved: the supplied label lands on the
// new token row (audit path).
func TestReissueBotToken_LabelPreserved(t *testing.T) {
	s := newReissueStore(t)
	owner := makeHuman(t, s, "alice", "alice-tok")
	agent := makeAgent(t, s, owner, "dev-bot")

	resp, err := ReissueBotToken(s, owner, "dev-bot", "ci-server")
	if err != nil {
		t.Fatalf("ReissueBotToken: %v", err)
	}

	tokens, err := s.ListTokensByCitizen(agent.ID)
	if err != nil {
		t.Fatalf("list tokens: %v", err)
	}
	var found bool
	for _, tok := range tokens {
		if tok.Token == resp.Token && tok.Label == "ci-server" {
			found = true
		}
	}
	if !found {
		t.Errorf("new token with label %q not found in token list: %+v", "ci-server", tokens)
	}
}
